### ISSUE TITLE
[Issue]: Water_Heater  operation_mode

### ISSUE THREAD

**Issue by pwwukpw** [speleolontra/daikin_residential_altherma#130]
Sorry to re raise an issue .  Since the move to water_heater I cannot get my automatons to function. I'm using syntax below to no avail. I've tried Heat Pump  and On as mode:

```
service: water_heater.set_operation_mode
target:
  entity_id: water_heater.altherma
data:
  operation_mode: Heat Pump
```

```
Logger: custom_components.daikin_residential_altherma.water_heater
Source: custom_components/daikin_residential_altherma/water_heater.py:219
Integration: Daikin Residential Controller for Altherma ([documentation](https://github.com/speleolontra/daikin_residential_altherma), [issues](https://github.com/speleolontra/daikin_residential_altherma/issues))
First occurred: 13:16:55 (8 occurrences)
Last logged: 13:30:12

Invalid tank state: Heat Pump
Invalid tank state: On
```
