### ISSUE TITLE
[Issue]: How to set boiler temp from an automation ?

### ISSUE THREAD

**Issue by avilleret** [speleolontra/daikin_residential_altherma#178]
I would like to set the boiler temp from an automation.
Unfortunately I can't find the boiler temp as an action target but only HVAC mode (I don't know what it is btw) and turn heat pump on and off.

<img width="397" alt="image" src="https://github.com/speleolontra/daikin_residential_altherma/assets/504914/b55dbe77-7da5-4d4e-9640-8801a51eb131">

Also if I create the automation manually, the Daikin device appears as "Unnamed device".

<img width="808" alt="image" src="https://github.com/speleolontra/daikin_residential_altherma/assets/504914/f11883b8-5905-4116-9d8a-fffc37ffda97">

Is it a bug or am I missing something ?

Thanks for you help. 
Here is my config file:  [config_entry-daikin_residential_altherma-20e4684f349c2e247c522d5f159c25e4.json.txt](https://github.com/speleolontra/daikin_residential_altherma/files/13033595/config_entry-daikin_residential_altherma-20e4684f349c2e247c522d5f159c25e4.json.txt)

**Comment by jwillemsen** [comment]
I am using this automation for setting the tank temperature

```
alias: TankTo48
description: Set Alterma Tank temperature to 48 at 3AM
trigger:
  - platform: time
    at: "05:00:00"
action:
  - service: water_heater.set_temperature
    data:
      temperature: 49
    target:
      entity_id: water_heater.altherma
mode: single
```
