### ISSUE TITLE
Change the schedule of heating and cooling from home assistant

### ISSUE THREAD

**Issue by trvrcr** [speleolontra/daikin_residential_altherma#56]
Hello,

I want to be able to change the schedule of the Altherma. This way in home assistant I can create an automation for the schedule to be changed based on the surplus energy of my solar Panels.

Is anyone up to help find a solution to this?
I already looked into the raw data file. And it is a value that is settable.

**Comment by jwillemsen** [comment]
This is currently not supported (also not by the daikin_residential integration). Currently I have no plans to add this support, when someone is interested, feel free to implement and open a pull request.

**Comment by helmuto** [comment]
Hi - first of all - thanks a lot for this HA integration. I installed it today - works nice.
I am currently only changing the target water temperature (manually) so that the heating process is running during the day where I got power from my solar panels. 
This could be automated if it would be possible to set the ATTR_TANK_TARGET_TEMPERATURE (expose as Action?).
Would this be possible? Since I have no HA experience I am not sure if I can implement this - but a push in the right direction would be really appreciated.
thanks, Helmut

**Comment by jwillemsen** [comment]
I use the automation below to lower the target tank temperature when the outside unit is too hot, it will use the backup heater at this moment to heat the water which drains power.

```
alias: LowerTankTemperature
description: Lower Alterma Tank temperature
trigger:
  - platform: time_pattern
    minutes: /10
condition:
  - condition: numeric_state
    entity_id: sensor.altherma_outside_temperature
    above: 24
  - condition: numeric_state
    entity_id: water_heater.altherma
    below: 46
    attribute: current_temperature
  - condition: time
    after: "10:00:00"
    before: "23:00:00"
action:
  - service: water_heater.set_temperature
    data:
      temperature: 33
    target:
      entity_id: water_heater.altherma
mode: single
```
