### ISSUE TITLE
Automations based on temperature don't work

### ISSUE THREAD

**Issue by thyeestes** [speleolontra/daikin_residential_altherma#65]
I have this integration installed in HA and I'm using a BRP069A78 unit. All information from the unit seems to be correctly displayed in my HA instance, however I'm not able to use the temperature sensors in automations.

#Not sure if this is related to https://github.com/speleolontra/daikin_residential_altherma/issues/48

Example automation:
```
alias: Notify when tank temp is at 60
description: ""
trigger:
  - platform: numeric_state
    entity_id: sensor.altherma_tank_temperature
    attribute: ""
    below: "51"
    for:
      hours: 0
      minutes: 0
      seconds: 0
condition: []
action:
  - service: notify.pushover
    data:
      message: Legionella programma uitgevoerd
mode: single
```
